### PR TITLE
Added Colocalization by Cross Correlation plugin

### PR DESCRIPTION
**Pull request by andmccall**
Just trying to add my new plugin to the list.

Andrew

### CODE REVIEW

**Comment by frauzufall** [comment]
Hi @andmccall, sorry it took me so long to respond! Can you please create this page on the wiki: https://imagej.net/Amccall and document your update site? Thank you!

**Comment by andmccall** [comment]
Hi @frauzufall, sorry about that. I didn't notice it had to be the update site name, not the plugin name. I've created the page and have it direct people to the Coloc by Cross Correlation page.

**Comment by frauzufall** [comment]
@andmccall that's just where I look for documentation before merging a PR here, thanks for adding the link!

**Comment by ctrueden** [comment]
@andmccall There doesn't have to be a page for the update site name—actually having one for each of the plugins is great. But it's nice, if in the markdown here, you can link to the right wiki page(s). If you look in the `sites.yml` you'll see quite a few update sites that do this.

**Pull request merged**
