### PR TITLE
Add unique IDs for update sites

### PR DESCRIPTION
**Pull request by ctrueden**
See cc5cf8dded80801b850b87458f2da47ffb54ddc6 for details.

### CODE REVIEW

**Comment by ctrueden** [comment]
> It would be great if we could check for uniqueness for each PR

Implemented in d03a61a021d10d6b12debac469df44e461b224d4.

**Comment by ctrueden** [comment]
And now with 701cee349011ec76f48bef943149dcdb62f71987, we check more thoroughly using `yamllint`. Although for now, we use `-d relaxed` since the linter warns about long lines, which we do not want to address.

**Comment by ctrueden** [comment]
Rebased over latest master, including ID for new CAMDU site.

@frauzufall Please merge when ready, if you are happy with it.

**Comment by frauzufall** [comment]
Merged with latest master, added missing hyphen, added test to detect duplicate keys and a basic README. Does this need to be rebased before merging the PR?

**Comment by ctrueden** [comment]
@frauzufall wrote:
> Does this need to be rebased before merging the PR @ctrueden?

I don't feel strongly. It looks like you already addressed the latest conflicts by merging master into this branch, so it's fine if you want to merge it to master as-is.

**Pull request merged**
