### PR TITLE
Update sites.yml

### PR DESCRIPTION
**Pull request by MarcoTarasco**

### CODE REVIEW

**Comment by frauzufall** [comment]
@MarcoTarasco thanks for the PR! I could not find documentation for this update site on the wiki, can you please create a page with usage notes or a link to existing documentation (e.g. https://imagej.net/ZFBONE) and let me know?

**Comment by MarcoTarasco** [comment]
@frauzufall I actually created by mistake another page at the beginning. That is why it was not available. As suggested by you, I have now a wiki page for ZFBONE linked to GitHub.

Thank you for the help,

Marco

**Comment by frauzufall** [comment]
@MarcoTarasco so sorry I missed your reply!! It's merged now.

**Comment by MarcoTarasco** [comment]
Thank you 😃

**Pull request merged**
