### PR TITLE
Update sites.yml

### PR DESCRIPTION
**Pull request by jiri-janacek**
Hi. I created some plugins wrapped in package Biomat, documented on https://imagej.net/Biomat with source on Git Hub.

Jiri Janacek, department of biomathematics, Institute of Physiology ASCR, Praha, Czech Republic
https://imagej.net/User:Biomat
jiri.janacek@fgu.cas.cz, http://www2.biomed.cas.cz/~janacek/

### CODE REVIEW

**Comment by imagejan** [comment]
The Travis CI build is [failing](https://github.com/imagej/list-of-update-sites/pull/11/checks?check_run_id=85140597) for this PR. @jiri-janacek can you please fix the indentation and *force-push* back to your branch to update this PR?

**Comment by ctrueden** [comment]
@imagejan @jiri-janacek Thanks to GitHub's online edit feature, I was able to easily fix the indentation in the web browser, without the rigamole of git on the CLI. So I went ahead and did it. We will see if the build passes. If so, then we can use "squash and merge" to keep the master branch history clean.

**Comment by ctrueden** [comment]
Thanks @jiri-janacek!

**Comment by jiri-janacek** [comment]
Thank you for help with indentation. I have no experience with GitHub and Travis yet. Editing the list in Chrome was probably not the right approach.
Best regards Jiri

**Comment by ctrueden** [comment]
No worries, @jiri-janacek. Editing online with Chrome is just fine. It's just that YAML is sensitive to whitespace. But catching these things early is exactly what Travis is for, so no harm done!

**Pull request merged**
