### PR TITLE
Add Spindle3D

### PR DESCRIPTION
**Pull request by tischi**

### CODE REVIEW

**Comment by ctrueden** [comment]
@turekg Why was this closed? Is there a commit resolving it? Or is the contribution rejected? Or did @tischi withdraw it?

**Comment by turekg** [comment]
@ctrueden @tischi asked for a review and I approved it

**Comment by ctrueden** [comment]
@turekg OK. But this PR was _closed_, as opposed to _merged_. And on master, the Spindle3D site is still not in `sites.yml`.

@tischi You wanted this added, right? If so, we can reopen and then merge it.

**Comment by turekg** [comment]
Darn it. Multi tasking overload 😜

**Comment by ctrueden** [comment]
All right, now reopened and merged! :+1:

**Pull request merged**
