### PR TITLE
Add TrackMate-Oneat

### PR DESCRIPTION
**Pull request by kapoorlab**
Adding TrackMate-oneat to the update site index.

### CODE REVIEW

**Comment by imagejan** [comment]
Thanks @kapoorlab! May I ask you to add some documentation page about your plugin to the https://imagej.net wiki?

**Comment by ctrueden** [comment]
@tinevez How do you feel about this work being mixed into the other `TrackMate-*` sites that you maintain? Personally, I think it would be better for @kapoorlab to choose a different prefix, to avoid the impression that this is an official TrackMate project. However, @tinevez if you give it your blessing then I'm OK with it. What do you think?

And @kapoorlab: as @imagejan says, please do add a wiki page, and link to it in the description here.

**Comment by kapoorlab** [comment]
I will just wait for @tinevez to reply about this and depending on that I will create a page in appropriate place for the wiki. Till then I will add some documentation on its github page: [TrackMate-oneat](https://github.com/Kapoorlabs-CAPED/TrackMate-oneat)

**Comment by kapoorlab** [comment]
Its been two days, there is no reply from @tinevez yet.

**Comment by tinevez** [comment]
Hello all.

I am perfectly happy with many others claiming their own TrackMate-* update sites. I think @haesleinhuepf already did with CliJ :) And it makes me perfectly happy to see TrackMate extended by others.

The only think I ask is to respect the capitalization:

> **T**rack**M**ate-**F**irstLetterOfExtensionCapitalized

What we can do to clarify responsibility is to make a table of known extensions on the main TrackMate wiki page, saying who is responsible for what.

Varun, I generally respond within 1 month unless holidays. Please ping me on twitter, on my direct messages, and here, only if this duration is exceeded.

**Comment by ctrueden** [comment]
Thanks @tinevez. Regarding the capitalization: it looks like [oneat](https://pypi.org/project/oneat/) might be one of those Python modules that insists it should be written in low case all the time, even at the beginning of a sentence, as evidenced by the "Examples" section of its PyPI page. However, it is also written capitalized "Oneat" in other places, including at the top, so we can probably get away with calling this extension "TrackMate-Oneat" instead of "TrackMate-oneat". OK for you, @kapoorlab?

**Comment by kapoorlab** [comment]
I can adhere to making oneat as Oneat everywhere to be consistent. Many thanks @tinevez, i will maintain this repo and it will be just as awesome as the promise it holds with many pretrained model releases and huge example datasets :).

**Comment by ctrueden** [comment]
PR cleaned up and merged.

@kapoorlab Now please edit [this wiki page](https://github.com/imagej/imagej.github.io/blob/main/_pages/plugins/trackmate/trackmate-oneat.md) and fill in the content.

**Comment by kapoorlab** [comment]
Will do in this weekend.

**Pull request merged**
