### PR TITLE
Added JIPipe update site

### PR DESCRIPTION
**Pull request by rumangerst**
Hello,

we successfully tested the update site for our new plugin and want it to be listed in the update manager for ease of access. 

The entry was added with all three maintainers and in alphabetical order. The YAML is valid according to yamllint.

Thanks!

### CODE REVIEW

**Comment by ctrueden** [comment]
@rumangerst Interesting project!

Could you please add a page at https://imagej.net/plugins/jipipe with a summary of the project? This will improve searchability from the main imagej.net site.

I'm also curious how this compares to KNIME. Why are you implementing this rather than embrace existing tools?

Finally, are you aware there is a project called [JPype](https://github.com/jpype-project/jpype) to use Java from Python? The PyImageJ project for example uses this. The name JIPipe is confusingly similar—do you think it's too late to choose a more clear name?

**Comment by rumangerst** [comment]
> Could you please add a page at https://imagej.net/plugins/jipipe with a summary of the project? This will improve searchability from the main imagej.net site.

Will do so!

> I'm also curious how this compares to KNIME. Why are you implementing this rather than embrace existing tools?

Very simple: It was never intended to be like KNIME. Initially the project was a simple GUI around the functionality of a macro for analyzing confrontation assays and grew into a VPL over time. It doesn't aim to be KNIME, but is aiming to be more something akin to Icy's protocol feature (https://icy.bioimageanalysis.org/plugin/protocols/) with more focus towards ImageJ. People who interacted with our tool liked it, so we oblige and publish it.

> Finally, are you aware there is a project called [JPype](https://github.com/jpype-project/jpype) to use Java from Python? The PyImageJ project for example uses this. The name JIPipe is confusingly similar—do you think it's too late to choose a more clear name?

No, I was not aware of JPype. And Google did not produce any software in this field that is named "JIPipe" when the name was decided approx 2 years ago. Now it's a bit too late I think, as plenty of documentation and training material was already produced to ready the publication.

I agree that there is potential for confusion, but I think it's quite low as JIPipe is an end user GUI program and JPype is a Python module. And I think developers (the audience who is interested in a Python module) would probably notice the differences. The vocalization is also a bit different: JPype I would pronounce as "jay - pipe", while JIPipe should be pronounced as "jii - pipe" (and we call it like that in the training videos).

We could also of course go with the full name in the index "Java Image Processing Pipeline (JIPipe)" if it helps or leave it off the index to let users manually add the item. The issue is that this name could be a bit too long for image.sc, as we *want* to work together with the community (if we're welcome of course).

**Comment by ctrueden** [comment]
Thanks @rumangerst for the info. The wiki page is great. And I understand about the name; it's probably fine. :+1:

**Comment by Thrameos** [comment]
For what it is worth, I tend to pronounce JPype as "Jay-Pie-Pee"  rather than "Jay-Pipe"  because it has nothing to do with "pipes", and much more to do with "Python".  But I am likely the odd man out.

**Comment by rumangerst** [comment]
@ctrueden Thank you!

@Thrameos Yes it's interesting to think about how to pronounce JPype. So we have the **J** = Java, then the **Py** = Python, but I think the "Pipe" is still valid, as we basically have some "pipe" between Java and Python. Except if the **Pe** means something else...

**Pull request merged**
