### PR TITLE
Update sites.yml

### PR DESCRIPTION
**Pull request by djpbarry**
All plugins that were associated with the CellMotility update site have been migrated to CALM

### CODE REVIEW

**Comment by ctrueden** [comment]
Thanks!

**Comment by imagejan** [comment]
Another orphanized entry in the updater...

The updater unfortunately doesn't know yet how to "forget" update sites, so if people don't know they can remove old sites (i.e. the ones below the last one in the alphabet), Fiji installations will collect a list of obsolete entries at the bottom of the update sites list.

Screen Shot 2019-03-19 at 20 41 16

@frauzufall, @ctrueden is this something the new updater will address? Should we keep a history of *removed* update sites (assembled from the wiki page history and this git repo) to sanitize Fiji installation once the updater v2 knows how to deal with them?

**Comment by frauzufall** [comment]
@imagejan thanks for pointing it out! I think one could mark manually added sites specially (probably already do that) which would make it easy to sort out and delete these (not manually added) entries which got deleted from the list. There are a few scenarios to handle additionally when it comes to manually added sites overlapping with the iist though. I'll make a plan

**Comment by frauzufall** [comment]
btw. the CALM update site is also such an orphan right now even though it's still in sites.yml, I fixed it [here](https://github.com/imagej/list-of-update-sites/pull/7/commits/94dd586d246ec530730eca4da8cd735724dc68c2), hope to merge it soon.

**Pull request merged**
