### PR TITLE
Change URL of SciView to sciview-buttercup.

### PR DESCRIPTION
**Pull request by kephale**
Change the URL of SciView to point to the latest named version `sciview-buttercup`.
Also add link to documentation.

### CODE REVIEW

**Comment by imagejan** [comment]
Question: will this lead to the updater listing a lot of "locally modified" files, because the name of the update site SciView is still the same, but the artifacts changed?

**Comment by kephale** [comment]
Maybe, I only had time to make this PR not to check for backwards compatibility.

**Comment by ctrueden** [comment]
Just a note that this PR is on [my immediate priority list](https://imagej.net/people/ctrueden#immediate-priorities) to investigate the backwards compatibility implications, and try to forge some best practices surrounding retirement, renames, and/or merges of update sites. See also [this chatlog](https://gitter.im/scenerygraphics/SciView?at=61f90c6c5dc6213cd40ddbef).

**Comment by ctrueden** [comment]
I keep pushing this back, and it's ridiculous, so I'm merging it. Worst-case scenario is that people with sciview update site content get some locally modified files warnings. It's not the end of the world. I did do some experiments a few weeks ago and could not produce any problematic behavior, but I already forgot the details, sorry. Let's just move forward and if there are problems, we'll know for next time.

**Comment by kephale** [comment]
Thank you!

**Pull request merged**
