### PR TITLE
List micron.ox.ac.uk mirrors of the imagej, fiji, and java-8 update sites

### PR DESCRIPTION
**Pull request by carandraug**
Add the Micron Oxford mirrors to the list of update sites. As proposed (but not discussed) in https://forum.image.sc/t/listing-update-sites-mirrors/70289

### CODE REVIEW

**Comment by ctrueden** [comment]
Thanks @carandraug for pushing this forward, and sorry for not responding to your proposal yet. I did see it, just busy with a Fiji release at the moment.

As written, I don't think this PR will accomplish what you want... it still specifies the sites.imagej.net update site URLs, as opposed to the Oxford ones. It's going to take me a little while to play with this and see how the Updater behaves in response to swapping out these core URLs with different ones. There is some also some hardcoded logic in the Updater code that might cause problems related to using these mirrors, I'm not sure. Investigation needed.

**Comment by carandraug** [comment]
> As written, I don't think this PR will accomplish what you want... it still specifies the sites.imagej.net update site URLs, as opposed to the Oxford ones. [...]

Ups. That's an embarrassing mistake. I have pushed another commit that does it.

> It's going to take me a little while to play with this and see how the Updater behaves in response to swapping out these core URLs with different ones.

There is also the use case of someone adding the mirrors without removing the core sites. I too don't know what happens in that case.

**Comment by hinerm** [comment]
@ctrueden I tested manually adding these sites. The updater is definitely confused if you enable and then immediately disable one of the euro mirrors, believing it needs to re-download everything from the original site (even though it doesn't).

But the sites just appearing in the listing seems benign...

**Comment by ctrueden** [comment]
I'm sorry for my long silence and ignoring this. I just have not had time to evaluate what the ramifications might be of doing this. @hinerm If you are confident it will be OK, then go ahead and do whatever you think is best! I definitely think exposing the Oxford mirror to more users would be super helpful to folks in geographic proximity.

**Pull request merged**
