### PR TITLE
Add Microglia-Morphometry

### PR DESCRIPTION
**Pull request by tischi**
Hi @imagejan,

Here's another try. I also check the yml file:

image

### CODE REVIEW

**Comment by tischi** [comment]
Hi @bogovicj 

Does that look good to you to be merged?

I think @imagejan is on holidays 🎄

**Review by bogovicj — APPROVED** [review]

**Comment by bogovicj** [comment]
@tischi 
Looks good to me, though I'm not familiar with the procedure for update sites, so don't feel super comfortable merging.
How does it usually go?

**Comment by imagejan** [comment]
Indeed I'm on vacation, which doesn't prevent me from being online from time to time. Merged.

(I'd like to note though that it's not part of my main job to merge pull requests on this repository, so being on vacation doesn't make a difference.)

**Comment by ctrueden** [comment]
The primary maintainers of this repository are me (@ctrueden), @hinerm, and @etadobson. However, anyone with write access to this repository is welcome to review and merge changes, as @imagejan often does (:pray:). The CI build checks for YAML build errors. The main things to look for in review are:

1. Consistency. Does it match the rest of the `sites.yml`? Is it in alphabetical order?
2. Validity. Does it look like a legitimate update site from a real user/developer? Or is it spammy?
3. Correctness. Does the CI build pass?

Assuming all three above look good, merging should be just fine.

**Comment by ctrueden** [comment]
Edit: I see that CI builds for PRs are not hooked up for some reason. I will try to fix that now.

**Comment by ctrueden** [comment]
I have now hooked up the CI to PR builds. It would have caught the problem with this PR, which is that the line `maintainers:` was missing. I have now fixed that error with fb0199aa3d9ce46c2065be3268781f8b453dbe27.

**Comment by tischi** [comment]
Thanks all!
 
And merry 🎄

**Pull request merged**
