### PR TITLE
Add MoBIE update site

### PR DESCRIPTION
**Pull request by tischi**

### CODE REVIEW

**Comment by frauzufall** [comment]
Hi @tischi, thanks for the PR! Can you please create a page like https://imagej.net/MoBIE describing your update site or pointing to existing documentation?

**Comment by tischi** [comment]
Hi @frauzufall,

I added some minimal information here: https://imagej.net/MoBIE
Do you know how to add an image to the page?
There are some buttons: embed file, but then I do not know how to upload one.

**Comment by imagejan** [comment]
@tischi wrote:
> Do you know how to add an image to the page?

The imagej.net wiki is running the mediawiki backend, so you'll first have to 
[upload an image](https://www.mediawiki.org/wiki/Help:Managing_files) and then [link/embed it](https://www.mediawiki.org/wiki/Help:Images) on the page.

**Comment by tischi** [comment]
@imagejan 
Thanks a lot.
Isn't it cute? 
https://imagej.net/MoBIE

**Comment by frauzufall** [comment]
Lovely @tischi! Thanks for adding the page!

**Pull request merged**
